# Generated by Django 5.0.2 on 2026-02-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('questions_count', models.IntegerField(default=0)),
                ('answers_count', models.IntegerField(default=0)),
                ('flags_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily Stats',
            },
        ),
        migrations.RemoveField(
            model_name='riskalert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trendanalysis',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyInsight',
        ),
        migrations.DeleteModel(
            name='RiskAlert',
        ),
        migrations.DeleteModel(
            name='TrendAnalysis',
        ),
    ]
