# Generated by Django 5.0.2 on 2026-02-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancerequest',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guidancerequest',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guidancerequest',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
