# Generated by Django 5.2.11 on 2026-03-01 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorshipReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('reminder_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('repeat_daily', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worship_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Worship Reminder',
                'verbose_name_plural': 'Worship Reminders',
                'db_table': 'worship_reminders',
            },
        ),
    ]
