# Generated by Django 5.2.11 on 2026-03-01 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='worshipreminder',
            old_name='reminder_time',
            new_name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='worshipreminder',
            name='content',
        ),
        migrations.RemoveField(
            model_name='worshipreminder',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='worshipreminder',
            name='repeat_daily',
        ),
        migrations.AddField(
            model_name='worshipreminder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.worshipcategory'),
        ),
        migrations.AddField(
            model_name='worshipreminder',
            name='repeat_rule',
            field=models.CharField(default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='worshipreminder',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='worshipreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worship_reminders_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='worshipreminder',
            table='reminders_v2',
        ),
    ]
