# Generated by Django 5.0.2 on 2026-02-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='body',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
    ]
