# Generated by Django 5.2.11 on 2026-03-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='item_type',
            field=models.CharField(choices=[('dhikr', 'Dhikr'), ('dua', 'Dua'), ('asmaul_husna', 'Asmaul Husna')], max_length=20),
        ),
    ]
