# Generated by Django 5.2.11 on 2026-03-01 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('duas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('arabic_text', models.TextField(blank=True, help_text='Store only if not quranic')),
                ('translation', models.TextField(blank=True, help_text='Store only if not quranic')),
                ('reference', models.CharField(blank=True, help_text='Hadith or other source', max_length=255)),
                ('is_quranic', models.BooleanField(default=False)),
                ('verse_reference', models.CharField(blank=True, help_text='Format: Surah:Ayah, e.g., 2:255', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dua_items', to='categories.worshipcategory')),
            ],
            options={
                'verbose_name': 'Dua Item',
                'verbose_name_plural': 'Dua Items',
                'db_table': 'dua_items',
            },
        ),
        migrations.DeleteModel(
            name='Dua',
        ),
    ]
