# Generated by Django 5.2.11 on 2026-03-01 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dhikr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arabic_text', models.TextField()),
                ('translation', models.TextField()),
                ('transliteration', models.TextField(blank=True)),
                ('count_limit', models.PositiveIntegerField(default=1, help_text='Number of times to recite')),
                ('category', models.CharField(default='General', max_length=100)),
                ('benefit', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dhikr',
                'verbose_name_plural': 'Dhikr Library',
                'db_table': 'dhikr_library',
            },
        ),
    ]
