# Generated by Django 5.2.11 on 2026-03-01 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('dhikr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DhikrItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arabic_text', models.TextField()),
                ('transliteration', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True)),
                ('repeat_default', models.PositiveIntegerField(default=1)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhikr_items', to='categories.worshipcategory')),
            ],
            options={
                'verbose_name': 'Dhikr Item',
                'verbose_name_plural': 'Dhikr Items',
                'db_table': 'dhikr_items',
            },
        ),
        migrations.CreateModel(
            name='UserDhikrLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_performed', models.DateTimeField(auto_now=True)),
                ('dhikr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dhikr.dhikritem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhikr_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Dhikr Log',
                'verbose_name_plural': 'User Dhikr Logs',
                'db_table': 'user_dhikr_logs',
                'unique_together': {('user', 'dhikr')},
            },
        ),
        migrations.DeleteModel(
            name='Dhikr',
        ),
    ]
