# Generated by Django 5.0.2 on 2026-02-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_entity__9535bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_timesta_19e18a_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
