# Generated by Django 5.0.2 on 2026-02-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
