# Generated by Django 5.2.11 on 2026-03-01 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('calculation_method', models.CharField(default='ISNA', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worship_prayer_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prayer Settings',
                'db_table': 'prayer_settings',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_reciter_id', models.UUIDField(blank=True, null=True)),
                ('translation_language', models.CharField(default='en', max_length=10)),
                ('adhan_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worship_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='AdhanAlarm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prayer_name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('offset_minutes', models.SmallIntegerField(default=0)),
                ('tone', models.CharField(default='default', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhan_alarms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adhan Alarm',
                'verbose_name_plural': 'Adhan Alarms',
                'db_table': 'adhan_alarms',
                'unique_together': {('user', 'prayer_name')},
            },
        ),
    ]
