# Generated by Django 5.2.11 on 2026-03-01 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
        ('prayer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='selected_reciter_id',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='selected_reciter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_selections', to='audio.reciter'),
        ),
    ]
