# Generated by Django 5.0.2 on 2026-02-19 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='answers.draftanswer')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruling_verified', models.BooleanField(default=False)),
                ('no_personal_opinion', models.BooleanField(default=False)),
                ('riba_addressed', models.BooleanField(default=False)),
                ('darurah_not_misused', models.BooleanField(default=False)),
                ('scholarly_source_exists', models.BooleanField(default=False)),
                ('respectful_tone', models.BooleanField(default=False)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='moderation.answerreview')),
            ],
        ),
    ]
