# Generated by Django 5.2.11 on 2026-03-01 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsmaulHusna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_arabic', models.CharField(max_length=255)),
                ('transliteration', models.CharField(max_length=255)),
                ('meaning', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Name of Allah',
                'verbose_name_plural': 'Names of Allah',
                'db_table': 'asmaul_husna',
            },
        ),
    ]
