# Generated by Django 5.0.2 on 2026-02-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('content_admin', 'Content Admin'), ('fiqh_reviewer', 'Fiqh Reviewer'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
