# Generated by Django 5.0.2 on 2026-02-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='madhhab',
            field=models.CharField(choices=[('hanafi', 'Hanafi'), ('shafii', "Shafi'i"), ('maliki', 'Maliki'), ('hanbali', 'Hanbali')], default='hanafi', max_length=20),
        ),
    ]
