# Generated by Django 5.0.2 on 2026-02-18 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('quran', "Qur'an"), ('hadith', 'Hadith'), ('ijma', 'Ijma (Consensus)'), ('qiyas', 'Qiyas (Analogy)')], max_length=20)),
                ('reference', models.CharField(max_length=255)),
                ('text_arabic', models.TextField(blank=True)),
                ('text_english', models.TextField()),
                ('source_book', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Madhhab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('salah', 'Salah'), ('sawm', 'Fasting'), ('zakat', 'Zakat'), ('hajj', 'Hajj'), ('nikah', 'Marriage'), ('muamalat', 'Financial')], max_length=50)),
                ('summary', models.TextField()),
                ('verdict', models.CharField(max_length=100)),
                ('ai_explanation_prompt', models.TextField(help_text='Instructions for AI to explain this ruling')),
                ('evidence', models.ManyToManyField(related_name='rulings', to='spiritual_intelligence_service.evidence')),
                ('madhhab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rulings', to='spiritual_intelligence_service.madhhab')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=255)),
                ('modification', models.TextField()),
                ('ruling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='spiritual_intelligence_service.ruling')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('ruling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='spiritual_intelligence_service.ruling')),
            ],
        ),
        migrations.CreateModel(
            name='UserDeenPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('goals_data', models.JSONField(default=dict)),
                ('weekly_review_notes', models.TextField(blank=True)),
                ('auto_summary', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deen_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('target_value', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='spiritual_intelligence_service.userdeenplan')),
            ],
        ),
        migrations.CreateModel(
            name='WorshipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('value', models.FloatField(default=1.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'timestamp'], name='spiritual_i_user_id_8d8069_idx'), models.Index(fields=['category'], name='spiritual_i_categor_c072ac_idx')],
            },
        ),
    ]
