# Generated by Django 5.0.2 on 2026-02-18 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_userreflection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Juzs',
                'ordering': ['number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ayahtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ayahtranslation',
            name='ayah',
        ),
        migrations.RemoveField(
            model_name='ayahtranslation',
            name='source',
        ),
        migrations.DeleteModel(
            name='RecitationSource',
        ),
        migrations.AlterUniqueTogether(
            name='userbookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userbookmark',
            name='ayah',
        ),
        migrations.RemoveField(
            model_name='userbookmark',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userreadingprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userreadingprogress',
            name='ayah',
        ),
        migrations.RemoveField(
            model_name='userreadingprogress',
            name='surah',
        ),
        migrations.RemoveField(
            model_name='userreadingprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userreflection',
            name='ayah',
        ),
        migrations.RemoveField(
            model_name='userreflection',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='ayah',
            options={'ordering': ['ayah_number_global']},
        ),
        migrations.RenameField(
            model_name='ayah',
            old_name='ayah_number',
            new_name='ayah_number_in_surah',
        ),
        migrations.RenameField(
            model_name='surah',
            old_name='ayah_count',
            new_name='total_ayahs',
        ),
        migrations.AlterUniqueTogether(
            name='ayah',
            unique_together={('surah', 'ayah_number_in_surah')},
        ),
        migrations.RemoveField(
            model_name='surah',
            name='revelation_type',
        ),
        migrations.AddField(
            model_name='ayah',
            name='audio_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ayah',
            name='ayah_number_global',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ayah',
            name='text_translation_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surah',
            name='revelation_place',
            field=models.CharField(default='Meccan', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surah',
            name='name_arabic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='surah',
            name='name_english',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='ayah',
            name='juz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.juz'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AyahTranslation',
        ),
        migrations.DeleteModel(
            name='TranslationSource',
        ),
        migrations.DeleteModel(
            name='UserBookmark',
        ),
        migrations.DeleteModel(
            name='UserReadingProgress',
        ),
        migrations.DeleteModel(
            name='UserReflection',
        ),
        migrations.RemoveField(
            model_name='ayah',
            name='juz_number',
        ),
        migrations.RemoveField(
            model_name='ayah',
            name='page_number',
        ),
    ]
