# Generated by Django 5.0.2 on 2026-02-19 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_userreflection_userbookmark_userreadingprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('provider', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField(max_length=500)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='quran.ayah')),
                ('reciter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='quran.reciter')),
            ],
            options={
                'unique_together': {('ayah', 'reciter')},
            },
        ),
        migrations.CreateModel(
            name='AyahTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quran.ayah')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quran.translationsource')),
            ],
            options={
                'unique_together': {('ayah', 'source')},
            },
        ),
    ]
