# Generated by Django 5.2.11 on 2026-03-01 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('surah_number', models.PositiveIntegerField()),
                ('ayah_number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('source_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'db_table': 'translations',
                'indexes': [models.Index(fields=['surah_number', 'ayah_number', 'language_code'], name='translation_surah_n_831e81_idx')],
                'unique_together': {('language_code', 'surah_number', 'ayah_number')},
            },
        ),
    ]
