# Generated by Django 5.2.11 on 2026-03-01 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorshipCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('dhikr', 'Dhikr'), ('dua', 'Dua')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='categories.worshipcategory')),
            ],
            options={
                'verbose_name': 'Worship Category',
                'verbose_name_plural': 'Worship Categories',
                'db_table': 'worship_categories',
            },
        ),
    ]
