# Generated by Django 5.2.11 on 2026-03-01 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('audio_base_url', models.URLField(max_length=500)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reciter',
                'verbose_name_plural': 'Reciters',
                'db_table': 'reciters',
            },
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surah_number', models.PositiveIntegerField()),
                ('ayah_number', models.PositiveIntegerField()),
                ('audio_url', models.URLField(max_length=500)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('reciter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='audio.reciter')),
            ],
            options={
                'verbose_name': 'Audio Track',
                'verbose_name_plural': 'Audio Tracks',
                'db_table': 'audio_tracks',
                'unique_together': {('surah_number', 'ayah_number', 'reciter')},
            },
        ),
    ]
