# Generated by Django 5.0.2 on 2026-02-19 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiqhRuling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ruling_text', models.TextField()),
                ('evidence_quran', models.JSONField(blank=True, default=list)),
                ('evidence_hadith', models.JSONField(blank=True, default=list)),
                ('scholar_name', models.CharField(max_length=200)),
                ('scholar_reference', models.TextField(blank=True)),
                ('fiqh_school', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rulings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiqh Ruling',
                'verbose_name_plural': 'Fiqh Rulings',
                'indexes': [models.Index(fields=['topic'], name='fiqh_fiqhru_topic_b6dc34_idx'), models.Index(fields=['verification_status'], name='fiqh_fiqhru_verific_4aec87_idx')],
            },
        ),
    ]
