# Generated by Django 5.0.2 on 2026-02-19 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiqh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiqhruling',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fiqhruling',
            name='scholar_name',
        ),
        migrations.AddField(
            model_name='fiqhruling',
            name='scholar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fiqhruling',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fiqhruling',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fiqhruling',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fiqhruling',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
