# Generated by Django 5.0.2 on 2026-02-19 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiqh', '0002_remove_fiqhruling_description_and_more'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_answer', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='DraftAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='questions.question')),
                ('used_rulings', models.ManyToManyField(related_name='used_in_drafts', to='fiqh.fiqhruling')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='answers.answer')),
                ('fiqh_ruling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiqh.fiqhruling')),
            ],
            options={
                'unique_together': {('answer', 'fiqh_ruling')},
            },
        ),
    ]
